### PR TITLE
fix 'invalid byte sequence in UTF-8' error

### PR DESCRIPTION
**Pull request by tooooolong**

### CODE REVIEW

**Comment by ruuts** [comment]
@tooooolong Nice inspiration http://robots.thoughtbot.com/post/42664369166/fight-back-utf-8-invalid-byte-sequences.
Just applied the same method, at least assets are compiling.

**Comment by tooooolong** [comment]
I will fix the error to fit ruby 1.8.7

**Comment by tooooolong** [comment]
Could you please upload a new version gem to Rubygems after you merge this.

**Comment by ndbroadbent** [comment]
Hi, unfortunately this is the incorrect way to solve the problem. Please see the discussion on #35

**Comment by ndbroadbent** [comment]
I might make the Uglifier configuration automatic in the next version:

```
# override default uglifier options so we don't mangle unicode
  config.assets.js_compressor = Uglifier.new(output: {ascii_only: true})
```

The issue should be solved if you put that in your application.rb

**Comment by tooooolong** [comment]
I'll try it. Thank you.

**Comment by tooooolong** [comment]
It solved my problem, thank you.

**Comment by tooooolong** [comment]
when i run asset precompile on my machine, it works

but i still get the UTF-8 error  when i deploy code to production machine.
and can fixed by this PR

**Comment by warp** [comment]
@tooooolong try deleting the compiled assets from your production machine the fix should work for subsequent runs of rake assets:precompile again

**Comment by GarPit** [comment]
Uglifier fix not working for me. Same issue - UTF-8 error

**Comment by davidguthu** [comment]
I'm seeing the same issue..  I traced it to a line in a comment in one of the included javascript files in a gem we added. . 

The line is commented
- Improvements by Sébastien Malot

If I remove that line then the compilation doesn't blow up.  I'm not sure why a comment is hanging it up, or .. really how to fix this..

**Pull request closed without merging**
