### PR TITLE
Add stub support

### PR DESCRIPTION
**Pull request by aaronjensen**
`stub` was added in `2.2.0`. It took me a while to figure out why it wasn't working when I realized it was effectively monkey patched out by `turbo-sprockets-rails3`. This adds it back in and bumps up the sprockets version dependency (which I realize may not be something you want to do). We could always detect support for it and optionally perform the stub removal.

### CODE REVIEW

**Comment by tim-vandecasteele** [comment]
Any reason why this is not taken along?

**Comment by ndbroadbent** [comment]
Not sure how this affects compatibility with other versions of Rails 3.2. I think 3-2-stable is pegged to a lower version of sprockets, IIRC. Maybe the optional stub removal would be a better idea in that case.

**Comment by aaronjensen** [comment]
No, it's pegged to 2.2.1: https://github.com/rails/rails/blob/3-2-stable/actionpack/actionpack.gemspec#L29

**Comment by aaronjensen** [comment]
Regardless, I bumped the version in the `turbo-sprockets-rails3` gemspec so people on older sprockets could still use the older version.

**Comment by romanbsd** [comment]
Took me a while to understand, why my CSS is screwed up. This feature is absolutely required...

**Comment by ndbroadbent** [comment]
Sorry for the huge delay, merged and pushed `0.3.11` to rubygems

**Comment by romanbsd** [comment]
Awesome! :+1:

**Comment by ndbroadbent** [comment]
Please do let me know if you have any problems after updating

**Pull request merged**
