### PR TITLE
"touch -c" now runs in slices of 100 (instead of 1000)

### PR DESCRIPTION
**Pull request by sibblingz**
We got a "Argument list too long" error during deployment, because our deploy-to path is quite lengthy. Ideally, this list should be sized by character count and not file count, but this will do for now.

### CODE REVIEW

**Comment by tuttinator** [comment]
+1 Awesome - thanks for that. I just ran into that issue now.

**Comment by ndbroadbent** [comment]
Great, thanks! Have released this change in `0.3.6`

**Comment by tuttinator** [comment]
Wow - thanks, amazingly fast response.

**Comment by sibblingz** [comment]
+1 that, very quick! I can get rid of my fork now.

**Pull request merged**
